# Generated by Django 5.1.6 on 2025-03-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitstats',
            name='weekly_completions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
